### PR TITLE
Fix for changed tox path

### PR DESCRIPTION
**Pull request by junaruga**
tox is installed at /usr/local/bin/tox on fedora:latest.
Previously it was installed at /usr/bin/tox.

### CODE REVIEW

**Comment by junaruga** [comment]
From today, fedora:latest became f27.
https://hub.docker.com/_/fedora/

**Comment by hroncok** [comment]
That's weird.

**Comment by hroncok** [comment]
```console
$ rpm -q python3-tox
python3-tox-2.7.0-2.fc27.noarch
$ rpm -ql python3-tox
/usr/bin/tox
/usr/bin/tox-quickstart
```

That's my actual F27 machine, will test with Docker as well.

**Comment by hroncok** [comment]
Oh, that goes form pip, now I get it. Sorry for the noise.

**Comment by junaruga** [comment]
Thanks for the reviewing. It was merged.

**Pull request merged**
