### PR TITLE
Revert monkeypatches in test_custom

### PR DESCRIPTION
**Pull request by ncoghlan**
Uses the pytest monkeypatch fixture to ensure that
changes to the Custom class are reverted after the
relevant tests.

### CODE REVIEW

**Comment by hroncok** [comment]
I think you've uncovered an issue, that the monkeypatching influenced other test and those test were not supposed to pass as they were.

https://github.com/ncoghlan/rpm-list-builder/blob/2dd627b6542d60dcaf1e838a4e1ec92e28cb2e98/rpmlb/yaml.py#L20 - this should also accept Path objects on older Pythons.

**Comment by ncoghlan** [comment]
@hroncok Ah, that would be why I didn't see the failure locally - I hadn't done a full tox run since fixing this. Update pushed with the extra `str()` call.

**Comment by hroncok** [comment]
Thanks. Now the Travis build pass. If you squash the first two commits, I'll merge.

**Comment by ncoghlan** [comment]
@hroncok Rebased & squashed.

**Pull request merged**
