### PR TITLE
Add simple recipe example that works on Fedora.

### PR DESCRIPTION
**Pull request by junaruga**
Related https://github.com/sclorg/rpm-list-builder/issues/66

I looks important to add sample recipe file that actually works on Fedora.
Because people can understand how it works easily.

Later I like adding below sample in Users Guide document as a tutorial.

```
$ rpmlb \
  -d custom \
  -b custom \
  -c tests/fixtures/custom/fedpkg_mock.yml \
  tests/fixtures/recipes/sl.yml sl
```

### CODE REVIEW

**Comment by hroncok** [comment]
I'd rather see at least 2 packages in there.

**Comment by junaruga** [comment]
ok just moment. I will rebase it.

**Comment by junaruga** [comment]
Rebased.
And below command works on Fedora.

```
$ rpmlb \
  --download custom \
  --build custom \
  --custom-file tests/fixtures/custom/fedpkg_mock.yml \
  --verbose \
  tests/fixtures/recipes/joke.yml \
  joke
```

**Comment by junaruga** [comment]
"Approved" changed to "Review required" again after rebase.
@hroncok can you change the settings for this repository? Because it is too strict.

**Comment by hroncok** [comment]
> can you change the settings for this repository? Because it is too strict.

This is what we have:

master

**Comment by junaruga** [comment]
@hroncok okay thank you for the information with the image. It looks good settings.

**Pull request merged**
