### PR TITLE
Extend initialization interface of a builder

### PR DESCRIPTION
**Pull request by khardix**
As discussed in sclorg#58 ([relevant discussion](https://github.com/sclorg/rpm-list-builder/pull/58#discussion_r127928250)), there is a need for a custom builder initialization not skipped on `--resume`. This PR extends the interface of `BaseBuilder.__init__` and relevant methods to allow for such initialization.

### CODE REVIEW

**Comment by khardix** [comment]
@junaruga, could you please go over the added docstrings for `BaseBuilder.{__init__,before,after}` and confirm that they correspond to what you have in mind for them?

After making sure that I understood them correctly, I will go over existing builders and refactor them to use the new `__init__` interface.

**Comment by khardix** [comment]
There was a syntax error on Py3.4 that was OK on later Pythons, oops 😄. Should be fixed now.

**Comment by khardix** [comment]
Rebased on current `master` branch.

**Comment by khardix** [comment]
Should be all set now. @junaruga, ready for review.

**Comment by junaruga** [comment]
It looks good to me!

**Pull request merged**
