### PR TITLE
Add additional flake8 plugins.

### PR DESCRIPTION
**Pull request by junaruga**
I want to enable 2 flake8 plugins. Those are used as `flake8` plugins.

- `flake8-isort`: it looks better than `flake8-import-order`. Because it covers detail cases. Ref https://github.com/gforcada/flake8-isort "Relaion to flake8-import-order"
- `pep8-naming`: It checks PEP-8's naming. https://github.com/PyCQA/pep8-naming
- `flake8-docstrings`: It looks better than flake8-pep257 . Because https://pypi.python.org/pypi/flake8-pep257/1.0.5 's home page: "Use https://gitlab.com/pycqa/flake8-docstrings instead.". I want to enable `flake8-docstrings` and `Sphinx` later. Not this PR.

If you like those plugins, I will fix the style errors in this PR.

Ref: plugins information.

```
(venv) $ flake8 --version
3.3.0 (flake8-colors: 0.1.0, flake8-docstrings: 1.1.0, pydocstyle: 2.0.0, flake8_isort: 2.1.3, mccabe: 0.6.1, naming: 0.4.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Linux
```

### CODE REVIEW

**Comment by hroncok** [comment]
Why not, but now the style test is failing.

**Comment by junaruga** [comment]
> Why not, but now the style test is failing.

Yes, the style test is failing.
https://travis-ci.org/sclorg/rpm-list-builder/builds/249285214

I intended

> If you like those plugins, I will fix the style errors in this PR.

Now I will fix those in this PR.

**Comment by junaruga** [comment]
Fixed!

**Comment by hroncok** [comment]
Please either split this to two commits, or at least reword the commit message to reflect the actual changes.

**Pull request merged**
